import EQUAL_TO from "./EQUAL_TO";
import GREATER_THAN from "./GREATER_THAN";
import GREATER_THAN_OR_EQUAL from "./GREATER_THAN_OR_EQUAL";
import LESS_THAN from "./LESS_THAN";
import LESS_THAN_OR_EQUAL from "./LESS_THAN_OR_EQUAL";
import NOT_EQUAL_TO from "./NOT_EQUAL_TO";

export default {
    EQUAL_TO,
    GREATER_THAN_OR_EQUAL,
    GREATER_THAN,
    LESS_THAN_OR_EQUAL,
    NOT_EQUAL_TO,
    LESS_THAN,
}