import AMPERSAND from "./AMPERSAND"
import COLON from "./COLON";
import COMMA from "./COMMA";
import DOT from "./DOT";
import LEFT_BRACE from "./LEFT_BRACE";
import LEFT_BRACKET from "./LEFT_BRACKET";
import LEFT_PARENTHESIS from "./LEFT_PARENTHESIS";
import RIGHT_BRACE from "./RIGHT_BRACE";
import RIGHT_BRACKET from "./RIGHT_BRACKET";
import RIGHT_PARENTHESIS from "./RIGHT_PARENTHESIS";
import SEMICOLON from "./SEMICOLON";
import SIMPLE_QUOTE from "./SIMPLE_QUOTE";
import DOUBLE_QUOTE from "./DOUBLE_QUOTE";

export default {
    AMPERSAND,
    COLON,
    COMMA,
    DOT,
    LEFT_BRACE,
    LEFT_BRACKET,
    LEFT_PARENTHESIS,
    RIGHT_BRACE,
    RIGHT_BRACKET,
    RIGHT_PARENTHESIS,
    SEMICOLON,
    SIMPLE_QUOTE,
    DOUBLE_QUOTE
}