import CALCULATIONPASSVALUE from "../CALCULATIONPASSVALUE";

test('CALCULATIONPASSVALUE reserved word', () => {
  expect('CALCULATIONPASSVALUE').toMatch(CALCULATIONPASSVALUE.PATTERN as RegExp);
  expect('something else').not.toMatch(CALCULATIONPASSVALUE.PATTERN as RegExp);
});