import CALCULATIONCURRENTPASS from "../CALCULATIONCURRENTPASS";

test('CALCULATIONCURRENTPASS reserved word', () => {
  expect('CALCULATIONCURRENTPASS').toMatch(CALCULATIONCURRENTPASS.PATTERN as RegExp);
  expect('something else').not.toMatch(CALCULATIONCURRENTPASS.PATTERN as RegExp);
});