import CREATEVIRTUALDIMENSION from "../CREATEVIRTUALDIMENSION";

test('CREATEVIRTUALDIMENSION reserved word', () => {
  expect('CREATEVIRTUALDIMENSION').toMatch(CREATEVIRTUALDIMENSION.PATTERN as RegExp);
  expect('something else').not.toMatch(CREATEVIRTUALDIMENSION.PATTERN as RegExp);
});