import DOUBLE_FORWARD_SLASHES from "./DOUBLE_FORWARD_SLASHES";
import DOUBLE_HYPHENS from "./DOUBLE_HYPHENS";
import FORWARD_SLASH_ASTERISK_PAIRS from "./FORWARD_SLASH_ASTERISK_PAIRS";

export default {
    DOUBLE_FORWARD_SLASHES,
    DOUBLE_HYPHENS,
    FORWARD_SLASH_ASTERISK_PAIRS
}